name       : vulkan-validation-layers
version    : 1.2.170.0
release    : 12
source     :
    - https://github.com/KhronosGroup/Vulkan-ValidationLayers/archive/sdk-1.2.170.0.tar.gz : 7c4f18b9d381505687e61e5cbc86aaeee590c290e60afb5bf451ebcd56e41283
license    : Apache-2.0
component  : xorg.display
libsplit   : no
summary    : Vulkan Validation Layers
description: |
    This package provides the Khronos official Vulkan validation layers.
patterns   :
    - /usr/include/vulkan
    - /usr/lib64/lib*.a
builddeps  :
    - pkgconfig(SPIRV-Tools)
    - pkgconfig(gl)
    - pkgconfig(vulkan)
    - pkgconfig(wayland-client)
    - pkgconfig(x11)
    - pkgconfig(xcb)
    - pkgconfig(xrandr)
    - glslang-devel
    - vulkan-headers
rundeps    :
    - vulkan
setup      : |
    %cmake_ninja \
        -DGLSLANG_INSTALL_DIR=%PREFIX%/bin \
        -DSPIRV_HEADERS_INSTALL_DIR=/usr/include/spirv \
        -DCMAKE_INSTALL_INCLUDEDIR=%PREFIX%/include \
        -DCMAKE_INSTALL_LIBDIR=lib%LIBSUFFIX% \
        -DBUILD_LAYER_SUPPORT_FILES=ON \
        -DBUILD_TESTS=OFF
build      : |
    %ninja_build
install    : |
    %ninja_install
