name       : vulkan-validation-layers
version    : 1.1.106.0
release    : 4
source     :
    - https://github.com/KhronosGroup/Vulkan-ValidationLayers/archive/sdk-1.1.106.0.tar.gz : 9ff52050b2cbc55f7c83d5ecbee287311ae31f03ee895ef0d6fc089b576b8caa
license    : Apache-2.0
component  : xorg.display
libsplit   : no
summary    : Vulkan Validation Layers
description: |
    This package provides the Khronos official Vulkan validation layers.
patterns   :
    - /usr/include/vulkan
    - /usr/lib64/lib*.a
builddeps  :
    - pkgconfig(SPIRV-Tools)
    - pkgconfig(gl)
    - pkgconfig(vulkan)
    - pkgconfig(wayland-client)
    - pkgconfig(x11)
    - pkgconfig(xcb)
    - pkgconfig(xrandr)
    - glslang-devel
    - vulkan-headers
rundeps    :
    - vulkan
setup      : |
    %cmake_ninja \
        -DCMAKE_INSTALL_LIBDIR=lib%LIBSUFFIX% \
        -DGLSLANG_INSTALL_DIR=%PREFIX%/bin \
        -DCMAKE_INSTALL_INCLUDEDIR=%PREFIX%/include/vulkan \
        -DBUILD_TESTS=OFF
build      : |
    %ninja_build
install    : |
    %ninja_install
