name       : vulkan-validation-layers
version    : 1.2.135.0
release    : 8
source     :
    - https://github.com/KhronosGroup/Vulkan-ValidationLayers/archive/sdk-1.2.135.0.tar.gz : 7a33aa13d9526da4deb945b3ccf5be9cf3c99fb4dfce2caf57640746c1c648d3
license    : Apache-2.0
component  : xorg.display
libsplit   : no
summary    : Vulkan Validation Layers
description: |
    This package provides the Khronos official Vulkan validation layers.
patterns   :
    - /usr/include/vulkan
    - /usr/lib64/lib*.a
builddeps  :
    - pkgconfig(SPIRV-Tools)
    - pkgconfig(gl)
    - pkgconfig(vulkan)
    - pkgconfig(wayland-client)
    - pkgconfig(x11)
    - pkgconfig(xcb)
    - pkgconfig(xrandr)
    - glslang-devel
    - vulkan-headers
rundeps    :
    - vulkan
setup      : |
    %cmake_ninja \
        -DCMAKE_INSTALL_LIBDIR=lib%LIBSUFFIX% \
        -DGLSLANG_INSTALL_DIR=%PREFIX%/bin \
        -DCMAKE_INSTALL_INCLUDEDIR=%PREFIX%/include/vulkan \
        -DBUILD_LAYER_SUPPORT_FILES=ON \
        -DBUILD_TESTS=OFF
build      : |
    %ninja_build
install    : |
    %ninja_install
