name       : vulkan-validation-layers
version    : 1.1.92.0
release    : 2
source     :
    - https://github.com/KhronosGroup/Vulkan-ValidationLayers/archive/sdk-1.1.92.0.tar.gz : 0fd13cba93d3468eebfb5e897afcd7e60948c2fe5628f9592f84e53da6bee68c
license    : Apache-2.0
component  : xorg.display
libsplit   : no
summary    : Vulkan Validation Layers
description: |
    This package provides the Khronos official Vulkan validation layers.
patterns   :
    - /usr/include/vulkan
    - /usr/lib64/lib*.a
builddeps  :
    - pkgconfig(SPIRV-Tools)
    - pkgconfig(gl)
    - pkgconfig(vulkan)
    - pkgconfig(wayland-client)
    - pkgconfig(x11)
    - pkgconfig(xcb)
    - pkgconfig(xrandr)
    - glslang-devel
rundeps    :
    - vulkan
    - devel : vulkan-devel
setup      : |
    %cmake_ninja \
        -DCMAKE_INSTALL_LIBDIR=lib%LIBSUFFIX% \
        -DGLSLANG_INSTALL_DIR=%PREFIX%/bin \
        -DCMAKE_INSTALL_INCLUDEDIR=%PREFIX%/include/vulkan \
        -DBUILD_TESTS=OFF
build      : |
    %ninja_build
install    : |
    %ninja_install
