name       : vulkan-validation-layers
version    : 1.2.176.0
release    : 13
source     :
    - https://github.com/KhronosGroup/Vulkan-ValidationLayers/archive/refs/tags/sdk-1.2.176.0.tar.gz : 531fca7db333e1e36f643dbad2d621d08f5f6a17b8b3745ef062c01079fe7631
license    : Apache-2.0
component  : xorg.display
libsplit   : no
summary    : Vulkan Validation Layers
description: |
    This package provides the Khronos official Vulkan validation layers.
patterns   :
    - /usr/include/vulkan
    - /usr/lib64/lib*.a
builddeps  :
    - pkgconfig(SPIRV-Tools)
    - pkgconfig(gl)
    - pkgconfig(vulkan)
    - pkgconfig(wayland-client)
    - pkgconfig(x11)
    - pkgconfig(xcb)
    - pkgconfig(xrandr)
    - glslang-devel
    - robin-hood-hashing
    - vulkan-headers
rundeps    :
    - vulkan
setup      : |
    %cmake_ninja \
        -DGLSLANG_INSTALL_DIR=%PREFIX%/bin \
        -DSPIRV_HEADERS_INSTALL_DIR=/usr/include/spirv \
        -DCMAKE_INSTALL_INCLUDEDIR=%PREFIX%/include \
        -DCMAKE_INSTALL_LIBDIR=lib%LIBSUFFIX% \
        -DBUILD_LAYER_SUPPORT_FILES=ON \
        -DBUILD_TESTS=OFF
build      : |
    %ninja_build
install    : |
    %ninja_install
